### ISSUE TITLE
Htcmusic apk

### ISSUE THREAD

**Issue by algor99** [archon810/apkmirror-public#13]
#### hello, I hope its a right place to ask. Its just I havent found any other place..
I have downloaded the latest version of htcmusic apk for my HTC10, and since it crushes all the time, I tried to uninstall it. 

#### there is no way to uninstall !!...
It just doesnt show/light  the "uninstall" tab in apps details. It is like disabled.

Please help me to uninstall it...

Thank you.

**Comment by archon810** [comment]
No, this is not the place.

**Comment by algor99** [comment]
Thank you, Artyom...

Sent from my HTC

----- Reply message -----
