### ISSUE TITLE
(enhancement) Please add Comments to apk apps

### ISSUE THREAD

**Issue by bluepak** [archon810/apkmirror-public#16]
#### Expected behavior
to be able to comment on APK apps, for example, I had the question of what is the difference between these two apps that for me they seem identical (except for the name and the release version numbers):

1. https://www.apkmirror.com/apk/google-inc/android-wear-smartwatch-android-wear/android-wear-smartwatch-android-wear-2-0-0-152767911-release/android-wear-smartwatch-android-wear-2-0-0-152767911-android-apk-download/download/

2. https://github.com/archon810/apkmirror-public/issues/new

#### Actual behavior
I am not able to read other people's comments on the app APK page nor able to post my own comments.

#### Steps to reproduce the problem
Go to any app page (like the ones I typed above) and scroll thru the whole page, you will not see a comments section.

**Comment by archon810** [comment]
@bluepak Comments are present on release and apk pages, like this one https://www.apkmirror.com/apk/google-inc/android-wear-smartwatch-android-wear/android-wear-smartwatch-android-wear-2-0-0-152767911-release/android-wear-smartwatch-android-wear-2-0-0-152767911-android-apk-download/.

Your report has a download landing page, which is where you arrive after clicking the Download button. The comment box is not expected on that page.
