### ISSUE TITLE
[BUG] App download numbers in "Popular in last 30 days" and on app page don't match

### ISSUE THREAD

**Issue by vissar2g** [archon810/apkmirror-public#17]
#### Expected behavior
App is 	
Google Account Manager 7.1.2. On the "Popular in Last 30 days page" it's listed as having 203k downloads. When clicking on it, however, the number of downloads is given as 80,344 . There are no multiple releases or similar apps that I could find that would be responsible for the discrepancy. 

#### Actual behavior
The two numbers should match. 

#### Steps to reproduce the problem
Go to main page and click on google account manager 7.1.2.

**Comment by archon810** [comment]
Thanks, this helped uncover a bug. We'll get it fixed up, @vissar2g.

**Comment by archon810** [comment]
Fixed.
