### ISSUE TITLE
RFE: Replace MD5 hashes w/ current SHA

### ISSUE THREAD

**Issue by TPS** [archon810/apkmirror-public#19]
#### Expected behavior
APKMirror should use & display current [SHA](https://en.m.wikipedia.org/wiki/Secure_Hash_Algorithms)s, @ least SHA-2.

#### Actual behavior
APKMirror still publishes only [MD5](https://en.m.wikipedia.org/wiki/MD5#Security), which has been broken since @ least late _2008_!

#### Steps to reproduce the problem
Navigate to any APK download page.  Only MD5 is shown for APK verification.

**Comment by archon810** [comment]
You have no idea how close we are to releasing just this 😲

**Comment by TPS** [comment]
I've been meaning to RFE this for months, but I'm glad it's close.

**Comment by archon810** [comment]
This is live. SHA-1, SHA-256, MD5 now showing for APK hashes. SHA-1 and SHA-256 for signatures.
