### ISSUE TITLE
Official Upload App

### ISSUE THREAD

**Issue by TPS** [archon810/apkmirror-public#21]
#### Expected behavior
An official app, once #19 is rolled out, to allow secure extraction & upload of version/variant APKs those apps already in APKMirror system, e.g., I've got binaries for Google & com.example.Malware apps, but app would verify only legit Google apps would be preverified & then attempt to be uploaded.  This could be part of APKMirror _site_ app mentioned in https://github.com/archon810/apkmirror-public/issues/3#issue-189885107, but not _necessarily_, since it'd have divergent enough purpose to be completely separate.  You could try to enforce as many security features as you'd like even before it hits whatever you all use for site security, such as not allowing completely _new_ apps to be uploaded this way, just new versions/variants.

#### Actual behavior
No such app, just cumbersome website upload after somehow separately "obtaining" APK.

#### Steps to reproduce the problem
All there is now is http://www.apkmirror.com/apk-upload/.  😑🤷

**Comment by archon810** [comment]
@TPS You can currently use ML Manager (http://www.androidpolice.com/2017/03/24/ml-manager-can-now-upload-apks-straight-apkmirror-apk-download) to easily upload APKs directly from your device. It's not the official app, but we worked closely with the developer to make integrated uploading happen.

The security features available on our end already prevent rogue APKs from going live.

**Comment by TPS** [comment]
In that case, make this a request for the upcoming official app.

N.B.: ML Manager is no longer open-source, which is troubling for some folks for a file manager.

**Comment by TPS** [comment]
Also, it's quite awkward to upload: Generally, I'll have multiple apps update really close together or @ same time due to ROM update, but ML Manager requires each APK to be sent individually.

**Comment by javiersantos** [comment]
Hi @TPS, ML Manager developer here. Thank you for your suggestion about a multiple upload feature.

I'm working hard to allow multiple uploads and it will be available in the upcoming 3.1 release.

**Comment by archon810** [comment]
By the way, the latest ML Manager beta allows for bulk APK uploads.
