### ISSUE TITLE
ApkMirror App

### ISSUE THREAD

**Issue by ansshkki** [archon810/apkmirror-public#23]
#### Expected behavior
This isn't issue, but why don't you make ApkMirror App for android... It will be perfect apk downloader app and it will be famous.

#### Steps to reproduce the problem

**Comment by TPS** [comment]
https://github.com/archon810/apkmirror-public/issues/21#issuecomment-305612161

**Comment by archon810** [comment]
We do not have an active plan for an Android app. You can use apps like ML Manager for uploading and APK Updater for downloading in the meantime.

**Comment by ansshkki** [comment]
Is there any intention for an app in the future?

**Comment by archon810** [comment]
There isn't at the moment, no.

**Comment by TacoTheDank** [comment]
*ahem*

https://labs.xda-developers.com/store/app/cf.vojtechh.apkmirror

**Comment by archon810** [comment]
That's not an official app, it's just a web wrapper.
