### ISSUE TITLE
Upload button don't work on firefox

### ISSUE THREAD

**Issue by jinkazama82it** [archon810/apkmirror-public#24]
On firefox the upload button don't work, I've clicked it but nothing.

**Comment by archon810** [comment]
Are we talking about mobile or desktop here? What version of Firefox? 

I just tried it on the mobile Firefox for Android, and the page correctly changed to http://www.apkmirror.com/apk-upload/. I'll test desktop when I get home.

**Comment by jinkazama82it** [comment]
Sorry, I haven't mentioned it, I have issue on Firefox desktop v54.0.1 (tomorrow I have in program to update some environment like java and flash probably something goes wrong on it, i don't know)

Il 09 luglio 2017 22:05:01 CEST, Artem Russakovskii <notifications@github.com> ha scritto:

**Comment by archon810** [comment]
Works well here. Not sure what the problem is on your end...

![image](https://user-images.githubusercontent.com/469543/28000493-e30aaddc-64da-11e7-92fc-8d9b9866cc8b.png)
