### ISSUE TITLE
Contact pages is broken

### ISSUE THREAD

**Issue by PaulBags** [archon810/apkmirror-public#30]
#### Expected behavior
The contact page requires an answer to a security question, I would expect that it ask one.

#### Actual behavior
No question is asked, making it impossible to use the contact form.

#### Steps to reproduce the problem
Try to use the contact page.

**Comment by archon810** [comment]
The contact page works fine. Maybe you're a bot trying to trick me into removing the challenge question :P

**Comment by PaulBags** [comment]
Ah, it's definitely not working, Firefox 55.0.2. The only question it asks is "are you human?", but doesn't accept Yes as an answer :p.

**Comment by archon810** [comment]
The question follows. You're supposed to complete the form by specifying the obvious missing bit.

**Comment by PaulBags** [comment]
Clearly, except the question doesn't follow.

**Comment by archon810** [comment]
It's a fill-in-the-blank. ___mirror.com.

**Comment by PaulBags** [comment]
Oh. It said 'mirror.com', which was some kind of link, about seven inches away from 'are you human?' and with no underscores - zero clue that it had anything to do with being a question, imo that's still broken.

**Comment by archon810** [comment]
I see an underscore.

![image](https://user-images.githubusercontent.com/469543/29942667-8db77c08-8e4b-11e7-8fb6-c352ede4dfc7.png)

**Comment by archon810** [comment]
I'll tweak the design so the box isn't as wide though. I think that's the confusing bit. And maybe try to minimize the space between the field and the word "mirror.com".

**Comment by PaulBags** [comment]
I was going to take a screenshot but it's been fixed. Honestly, both fill in the blank & the underscores weren't there, and mirror.com was on the same line as are you human. Underneth was an input field, probably the one that's currently the underscores.

**Comment by archon810** [comment]
Better:

![image](https://user-images.githubusercontent.com/469543/29943346-10e6b4fc-8e4e-11e7-9979-cecdedbd4422.png)
