### ISSUE TITLE
Pushbullet channels not updating

### ISSUE THREAD

**Issue by PaulBags** [archon810/apkmirror-public#31]
#### Expected behavior
When apks get updated links should be pushed to channels

#### Actual behavior
Channels are silent, RSS still works (but is useless in 2017)

#### Steps to reproduce the problem
Follow a channel, notice that updates don't happen.

**Comment by archon810** [comment]
Unfortunately, this is out of my hands. I've reported the issue to Pushbullet and have been regularly trying to get in touch and have it fixed, but I've been unsuccessful. 

https://twitter.com/ArtemR/status/902998766952693760

**Comment by TPS** [comment]
How weird!  I'm getting all Google channel's updates just fine.  Is it a particular set of channels that's not working?

**Comment by archon810** [comment]
I only monitor the main channel for everything, and it broke after we switched to forced https. Looks like the Pushbullet team fixed whatever broke today.
