### ISSUE TITLE
Error after upload 

### ISSUE THREAD

**Issue by roman313** [archon810/apkmirror-public#35]
#### Expected behavior
Vlc 2.5.4 arm64 

#### Actual behavior
Vlc 2.5.4 arm without my name (Unknown name)

**Comment by archon810** [comment]
Yours just wasn't published yet and was still in the queue. There's no issue here.

**Comment by roman313** [comment]
I'm send again, and now it's ok

⁣Отправлено с помощью BlueMail ​

На 10 окт. 2017 г., 19:09, в 19:09, Artem Russakovskii <notifications@github.com> написал:>Yours just wasn't published yet and was still in the queue. There's no
