### ISSUE TITLE
Mi Fit apk - no installation possible

### ISSUE THREAD

**Issue by sette1** [archon810/apkmirror-public#39]
#### Expected behavior
till Mi Fit 3.1.3.2 install was no problem (android 7.0)

#### Actual behavior
Mi Fit 3.1.3 and Mi Fit 3.1.5 installation not possible - package damaged

**Comment by archon810** [comment]
This is not an issue with APK Mirror, it's some incompatibility between your device and the APK. See comments where some people are saying it doesn't work for them, and others saying it does.

**Comment by sette1** [comment]
Ok thanks,

the actual version 3.1.6.1 works fine again :)

 

regards

 

Von: Artem Russakovskii [mailto:notifications@github.com] 
Gesendet: Samstag, 18. November 2017 02:48
An: archon810/apkmirror-public <apkmirror-public@noreply.github.com>
Cc: sette1 <sette1@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [archon810/apkmirror-public] Mi Fit apk - no installation possible (#39)

 

Closed #39 <https://github.com/archon810/apkmirror-public/issues/39> .
