### ISSUE TITLE
Whatsapp profile pic & twitter thumbnails are distorted 

### ISSUE THREAD

**Issue by harshalmodak** [archon810/apkmirror-public#4]
#### Expected behavior
I expect thumbnails of twitter images looks the way they suppose to be. Whatsapp profile picture cropping must work with whole image.

#### Actual behavior
When I select an image to set as a profile picture in whatsapp the crop function shows only 10% of complete photo and I am not able to scroll over rest of the image. In twitter, I am seeing stretched thumbnails of images.

Any help to fix this will be appreciable.

#### Steps to reproduce the problem
I have unlocked my one plus 3 and changed its dpi to 400.

**Comment by archon810** [comment]
This does not appear to be a bug in the apkmirror.com website functionality. Please contact Twitter and Whatsapp directly with your issues.
