### ISSUE TITLE
CSR Racing 2 APK are distributed in two versions but APKMirror accept only one

### ISSUE THREAD

**Issue by accdias** [archon810/apkmirror-public#41]
#### Expected behavior
Upload two different version of the same release and made they both available.

#### Actual behavior
Since the "external" version of the APK is the same, when I upload the second package, it overwrites the first.

#### Steps to reproduce the problem
Get the two versions of the same release of CSR Racing 2 APK (low quality and high quality graphics, respectively).
Upload the first version
Upload the second version

**Comment by archon810** [comment]
The APKs you uploaded are both exactly the same. Binary equal.

**Comment by accdias** [comment]
That is true for the last two I sent and I did that because the one I sent before was take too long to be published and I assumed I did something wrong.

I can send you both two APKs for comparison, if needed. How do I do that?

**Comment by archon810** [comment]
Go ahead and upload to apk mirror the 2nd one that's not already there, and I'll take a look.

**Comment by accdias** [comment]
I've made them available at my Mega drive. Here are the links:

com.naturalmotion.customstreetracer2-1.14.1.1854.apk	
https://mega.nz/#!FuBGRQAD!_KVTc8eQwWWjhFh5atqAlPfkVleQVpYLI87Ykc1sj_M

com.naturalmotion.customstreetracer2-1.14.1.1854.apk	
https://mega.nz/#!JrYl3JKT!smzRzANme_zWLmQa3c1g_MMMhYbhw89imxaOKNzaRdU

**Comment by accdias** [comment]
OK. I will upload the 1854 version to overwrite the 1855 (I guess those versions are internal).

**Comment by accdias** [comment]
Alright. Just uploaded the new one to APKMirror as you requested.

**Comment by archon810** [comment]
OK, pushed live. It's possible that I've been deleting the lower internal version APK for each release because they look slightly older, and I don't like to have dupes, but I'll keep this in mind.

**Comment by accdias** [comment]
Thanks a lot. It's really appreciated. :-)

**Comment by accdias** [comment]
Just one last question? Is it possible to host OBB files as well? Is there a way to check them against the publisher's keys?

**Comment by archon810** [comment]
That's the worst part. OBBs are not signed, so we'll never be able to accept them as uploads, only as those we download ourselves. But we'll need to heavily upgrade storage before then, and we're not ready for that kind of upgrade yet.

**Comment by accdias** [comment]
No worries. I've imagined that would be the cause. Thanks again and keep up with the excellent work you've doing.
