### ISSUE TITLE
No search results found with "maps beta" text

### ISSUE THREAD

**Issue by MihirGosai** [archon810/apkmirror-public#7]
#### Expected behavior
"Beta" version APK list having "Maps" text in title

#### Actual behavior
No results found

#### Steps to reproduce the problem
Search apk with "maps beta" text

**Comment by archon810** [comment]
Thanks for the report. I can reproduce this. We'll get it fixed. The special markers, like alpha and beta, should be part of the searchable strings.

**Comment by archon810** [comment]
This is fixed now.
