### ISSUE TITLE
Please include Arabroid Apps and Games on your Android Market

### ISSUE THREAD

**Issue by AshrafSello** [archon810/apkmirror-public#8]
#### Expected behavior
Hello,
I will be so glad if i'll find all my android apps and games next time i search your android market :)
Here is my link on google play to include my apps and games on your android market place:
https://play.google.com/store/apps/dev?id=6493557889401293855
Best regards,
Ashraf Sello
Arabroid

#### Actual behavior
Thank You

**Comment by archon810** [comment]
This isn't the right place for this sort of request.

**Comment by archon810** [comment]
P.S. Sorry, it would be denied anyway.
