### ISSUE TITLE
Android Version is not included in variant texts of "Opera browser - news & search" apk post

### ISSUE THREAD

**Issue by MihirGosai** [archon810/apkmirror-public#9]
#### Expected behavior
Opera browser - news & search 41.2.2246.111806 (arm) (Android 4.1+)
Opera browser - news & search 41.2.2246.111806 (arm) (Android 6.0+)

#### Actual behavior
Opera browser - news & search 41.2.2246.111806 (arm)
Opera browser - news & search 41.2.2246.111806 (arm)

#### Steps to reproduce the problem
Visit apk page of "Opera browser - news & search"
E.g. http://www.apkmirror.com/apk/opera-software-asa/opera/opera-41-2-2246-111806-release/opera-browser-news-search-41-2-2246-111806-android-apk-download/

**Comment by archon810** [comment]
Thanks, fixed it.

**Comment by MihirGosai** [comment]
Fixed quickly but "DPI" specifier nodpi is not required.
